# Generated by Django 3.1.7 on 2021-03-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
