# Generated by Django 3.1.7 on 2021-03-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210326_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
