# Generated by Django 3.1.7 on 2021-03-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_pricing_stripe_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='stripe_price_id',
        ),
    ]
